import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import PageHero from '../components/PageHero';
import { useLanguage } from '../context/LanguageContext';
import { useMarketplace } from '../context/MarketplaceContext';
import { formatDateTimeGmt3 } from '../lib/dateTime';
function AdminPage() {
    const { copy, language, translateCatalogText, translateListingStatus, translateOrderStatus } = useLanguage();
    const { advanceOrderStatus, listingStatuses, listings, orders } = useMarketplace();
    const totalUnits = listings.reduce((sum, listing) => sum + listing.inventory, 0);
    const lowStockCount = listings.filter((listing) => listing.inventory > 0 && listing.inventory <= 5).length;
    const outOfStockCount = listings.filter((listing) => listing.inventory === 0).length;
    const inventoryValue = listings.reduce((sum, listing) => sum + listing.price * listing.inventory, 0);
    const stockStats = [
        { label: copy.admin.stockCards.totalUnits, value: String(totalUnits) },
        { label: copy.admin.stockCards.lowStock, value: String(lowStockCount) },
        { label: copy.admin.stockCards.outOfStock, value: String(outOfStockCount) },
        { label: copy.admin.stockCards.stockValue, value: `${inventoryValue.toFixed(3)} BHD` },
    ];
    return (_jsxs("main", { className: "page-stack", children: [_jsx(PageHero, { variant: "admin", kicker: copy.admin.heroKicker, title: copy.admin.heroTitle, summary: copy.admin.heroSummary, aside: _jsxs(_Fragment, { children: [_jsx("p", { className: "card-label", children: copy.admin.planeLabel }), _jsx("p", { children: copy.admin.planeSummary })] }) }), _jsxs("section", { className: "ops-board", children: [_jsxs("div", { className: "section-heading compact", children: [_jsx("p", { className: "section-kicker", children: copy.admin.stockStatsKicker }), _jsx("h2", { children: copy.admin.stockStatsTitle })] }), _jsx("div", { className: "metric-grid admin-stock-grid", children: stockStats.map((item) => (_jsxs("article", { className: "metric-card", children: [_jsx("p", { className: "card-label", children: item.label }), _jsx("strong", { children: item.value })] }, item.label))) })] }), _jsxs("section", { className: "ops-board", children: [_jsxs("div", { className: "section-heading compact", children: [_jsx("p", { className: "section-kicker", children: copy.admin.queuesKicker }), _jsx("h2", { children: copy.admin.queuesTitle })] }), _jsx("div", { className: "queue-grid", children: copy.admin.queues.map((item) => (_jsx("article", { className: "queue-card", children: _jsx("p", { children: item }) }, item))) })] }), _jsxs("section", { className: "split-panel admin-split-panel", children: [_jsxs("div", { className: "split-copy", children: [_jsx("p", { className: "section-kicker", children: copy.admin.orderKicker }), _jsx("h2", { children: copy.admin.orderTitle }), _jsx("div", { className: "queue-grid admin-order-grid", children: orders.map((order) => {
                                    const listing = listings.find((item) => item.id === order.listingId);
                                    return (_jsxs("article", { className: "queue-card", children: [_jsx("p", { className: "card-label", children: order.id }), _jsx("h3", { children: listing ? translateCatalogText(listing.title) : order.listingId }), _jsx("p", { children: order.buyer }), _jsxs("p", { className: "microcopy", children: ["Ordered at: ", formatDateTimeGmt3(order.createdAt, language)] }), _jsxs("div", { className: "listing-footer", children: [_jsx("strong", { children: translateOrderStatus(order.status) }), _jsx("span", { children: translateListingStatus(listingStatuses[order.listingId] ?? listing?.status ?? 'live') })] }), _jsx("button", { type: "button", className: "button button-secondary order-action", onClick: () => void advanceOrderStatus(order.id), disabled: order.status === 'delivered', children: order.status === 'delivered' ? copy.admin.orderComplete : copy.admin.advanceOrder })] }, order.id));
                                }) })] }), _jsxs("div", { className: "control-room", children: [_jsxs("div", { className: "control-room-header", children: [_jsx("p", { className: "card-label", children: copy.admin.snapshotLabel }), _jsx("span", { children: copy.admin.snapshotState })] }), listings.map((listing) => (_jsxs("div", { className: "control-metric", children: [_jsx("strong", { children: translateCatalogText(listing.title) }), _jsx("span", { children: translateListingStatus(listingStatuses[listing.id] ?? listing.status) })] }, listing.id)))] })] }), _jsxs("section", { className: "rails-panel", children: [_jsxs("div", { className: "section-heading compact", children: [_jsx("p", { className: "section-kicker", children: copy.admin.responsibilitiesKicker }), _jsx("h2", { children: copy.admin.responsibilitiesTitle })] }), _jsx("div", { className: "rails-grid", children: copy.admin.rails.map((item) => (_jsxs("article", { className: "rail-card", children: [_jsx("h3", { children: item.title }), _jsx("p", { children: item.summary })] }, item.title))) })] })] }));
}
export default AdminPage;
